/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/

// Code generated by azure-service-operator-codegen. DO NOT EDIT.

// Package v20250101preview contains API Schema definitions for the insights v20250101preview API group
// +groupName=insights.azure.com
package v20250101preview
